import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Sidebar from "./sidebar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <div className="flex min-h-screen">
          <Sidebar />
          <main className="flex-1 bg-[#f8f9fb] min-h-screen p-0">{children}</main>
        </div>
      </body>
    </html>
  );
}
